-- Structural snapshot from the connected project; no customer data.
create table public.avances_obra (
  "id" uuid default gen_random_uuid() not null,
  "obra_id" uuid not null,
  "tecnico_id" uuid,
  "fase" character varying(50) not null,
  "nota" text not null,
  "fotos" text[] default '{}'::text[],
  "created_at" timestamp with time zone default now()
);
create table public.chats (
  "id" bigint generated by default as identity not null,
  "telefono" text,
  "mensaje_cliente" text,
  "respuesta_ia" text,
  "created_at" timestamp with time zone default timezone('utc'::text, now())
);
create table public.clientes (
  "id" uuid default gen_random_uuid() not null,
  "nombres" character varying(100) not null,
  "apellidos" character varying(100) not null,
  "numero_cedula" character varying(20) not null,
  "direccion" text,
  "telefono_1" character varying(20) not null,
  "telefono_2" character varying(20),
  "correo_electronico" character varying(150) not null,
  "fecha_nacimiento" date,
  "tipo_cliente" character varying(50) default 'Prospecto'::character varying,
  "created_at" timestamp with time zone default now()
);
create table public.obras (
  "id" uuid default gen_random_uuid() not null,
  "id_obra" character varying(20) not null,
  "cliente_id" uuid not null,
  "tecnico_id" uuid,
  "categoria_obra" character varying(50) not null,
  "descripcion" text,
  "fase_actual" character varying(50) default 'Diseño'::character varying,
  "porcentaje_avance" integer default 0,
  "fecha_entrega_estimada" date,
  "slug_tracking" character varying(50) not null,
  "estado" character varying(50) default 'Activa'::character varying,
  "created_at" timestamp with time zone default now(),
  "calificacion_estrellas" integer,
  "resena_comentario" text,
  "resena_fecha" timestamp with time zone
);
create table public.tecnicos (
  "id" uuid default gen_random_uuid() not null,
  "codigo_id" character varying(20) not null,
  "nombres" character varying(100) not null,
  "apellidos" character varying(100) not null,
  "numero_cedula" character varying(20) not null,
  "direccion" text,
  "telefono_1" character varying(20) not null,
  "correo" character varying(150),
  "activo" boolean default true,
  "created_at" timestamp with time zone default now()
);
alter table public.avances_obra add constraint "avances_obra_pkey" PRIMARY KEY (id);
alter table public.chats add constraint "chats_pkey" PRIMARY KEY (id);
alter table public.clientes add constraint "clientes_numero_cedula_key" UNIQUE (numero_cedula);
alter table public.clientes add constraint "clientes_pkey" PRIMARY KEY (id);
alter table public.obras add constraint "obras_id_obra_key" UNIQUE (id_obra);
alter table public.obras add constraint "obras_pkey" PRIMARY KEY (id);
alter table public.obras add constraint "obras_porcentaje_avance_check" CHECK (((porcentaje_avance >= 0) AND (porcentaje_avance <= 100)));
alter table public.obras add constraint "obras_slug_tracking_key" UNIQUE (slug_tracking);
alter table public.tecnicos add constraint "tecnicos_codigo_id_key" UNIQUE (codigo_id);
alter table public.tecnicos add constraint "tecnicos_numero_cedula_key" UNIQUE (numero_cedula);
alter table public.tecnicos add constraint "tecnicos_pkey" PRIMARY KEY (id);
alter table public.avances_obra add constraint "avances_obra_obra_id_fkey" FOREIGN KEY (obra_id) REFERENCES obras(id) ON DELETE CASCADE;
alter table public.avances_obra add constraint "avances_obra_tecnico_id_fkey" FOREIGN KEY (tecnico_id) REFERENCES tecnicos(id);
alter table public.obras add constraint "obras_cliente_id_fkey" FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE CASCADE;
alter table public.obras add constraint "obras_tecnico_id_fkey" FOREIGN KEY (tecnico_id) REFERENCES tecnicos(id) ON DELETE SET NULL;
